### PR TITLE
Linting and refactoring

### LINKED ISSUE #30: add linting for style consistency

### PR DESCRIPTION
**Pull request by gxavier38**
Resolves #30 and #35 
Linter configs taken from catamaran repo

### CODE REVIEW

**Comment by lucyq** [comment]
Is browser.html the old html demo file?

**Comment by lucyq** [comment]
How is the demo currently receiving the module code?

I'm getting the following error:
screen shot 2018-06-11 at 4 23 32 pm

**Comment by gxavier38** [comment]
All of those issues were fixed in this commit https://github.com/hicsail/constellation-js/pull/39/commits/2cd4c5f9ae67544f400327b523589eb91d2fd554
But that's on another branch

I mainly work off browser.html and only update client.html at the end. 
Forgot to do that here

**Comment by gxavier38** [comment]
Nevermind it doesn't.
Fixing it now

**Comment by lucyq** [comment]
outdated. will review D3 branch

**Pull request closed without merging**
